Repository ultimateBroK/fuze_music_player, pull requests merged in 2024-06, with the labels that each got.

#22 Cập nhật thêm library và PlayerActivity
  app/build.gradle.kts
  app/src/main/java/com/android/fuze_music_player/PlayerActivity.java
  gradle/libs.versions.toml
Labels: Review, Frontend

#24 Ft/add SongHistoryService
  app/src/main/java/com/android/fuze_music_player/model/SongHistory.java
  app/src/main/java/com/android/fuze_music_player/service/IHistoryService.java
  app/src/main/java/com/android/fuze_music_player/service/SongHistoryService.java
Labels: Backend, API

#30 Xóa các activity lỗi, cập nhật activity mới và bổ sung cho activity sẵn có
  app/src/main/java/com/android/fuze_music_player/History_Screen.java
  app/src/main/java/com/android/fuze_music_player/Last_added_Screen.java
  app/src/main/java/com/android/fuze_music_player/Music_item.java
  app/src/main/java/com/android/fuze_music_player/PlayerActivity.java
  app/src/main/java/com/android/fuze_music_player/Queue.java
  app/src/main/java/com/android/fuze_music_player/activity/PlayerActivity.java
  app/src/main/java/com/android/fuze_music_player/activity/QueueActivity.java
  app/src/main/java/com/android/fuze_music_player/adapter/QueueAdapter.java
  app/src/main/java/com/android/fuze_music_player/adapter/SongAdapter.java
  app/src/main/java/com/android/fuze_music_player/adapter/ViewPagerAdapter.java
  app/src/main/java/com/android/fuze_music_player/music_player.java
Labels: Feature, Enhancement, High
